//! Step 8.5a Phase 4.2 — scalar-parity (reference-based) on
//! step0/3/6/7. step8 excluded per α scope.
//!
//! # Why the reference architecture
//!
//! Comparing `x_amg` directly to `x_jacobi` at their convergence
//! tolerances is dominated by
//! `‖x_cg − x_exact‖ ≲ κ(A) · tol_cg` — the CG truncation
//! error. For poorly-conditioned systems (step0: κ ≈ 10⁵) this
//! is `10⁵ · 10⁻⁸ = 10⁻³`, well above any arbitrary "1e-5
//! parity" threshold. Measuring `rel_diff(x_amg, x_jacobi)`
//! conflates the two solvers' truncation errors and produces a
//! bound that neither solver can meet individually.
//!
//! Instead, Phase 4.2 tests each solver INDEPENDENTLY against a
//! high-precision reference `x_ref` generated by `bin/gen_
//! reference_solutions`. The scalar-parity bound for each solver
//! is derived algebraically from the triangle inequality:
//!
//! ```text
//!   ‖x_test − x_ref‖ ≤ ‖x_test − x*‖ + ‖x_ref − x*‖
//!                   ≤ κ·tol_test + κ·tol_ref
//!                   = κ · (tol_test + tol_ref)
//! ```
//!
//! so the threshold is `C · κ · (tol_test + tol_ref)`, with
//! `C = 3` absorbing the undetermined constant in the truncation
//! bound. Both the condition-number estimate `κ` and the
//! reference-precision `tol_ref` are measured empirically during
//! reference generation and serialised alongside `x_ref` in the
//! reference file.
//!
//! If either `x_jacobi(tol=1e-8)` or `x_amg(tol=1e-8)` exceeds its
//! per-case threshold against `x_ref`, that solver is producing a
//! wrong answer within the algebraic tolerance budget — a real
//! bug. If both pass, both solvers are correct to CG truncation
//! precision.

use std::path::PathBuf;

use ymir_core::tectonics_v2::field::Field2D;
use ymir_core::tectonics_v2::stokes::amg::{AmgConfig, AmgPreconditioner};
use ymir_core::tectonics_v2::stokes::nullspace;
use ymir_core::tectonics_v2::stokes::operator::{
    apply_momentum, apply_tangent, StokesGrid, TangentContext,
};
use ymir_core::tectonics_v2::stokes::precond::VelocityJacobi;
use ymir_core::tectonics_v2::stokes::snapshot::{
    field_from_vec, LinearStokesSnapshot, ReferenceSolution,
};
use ymir_core::tectonics_v2::stokes::solver::{ConjugateGradient, LinearSolver};
use ymir_core::tectonics_v2::stokes::sparse_assembly::assemble_picard_csr;

/// Triangle-inequality constant absorbing undetermined theoretical
/// factors in the CG truncation bound `‖x_cg − x*‖ ≲ κ · tol`.
/// `C = 3` is loose enough to survive reasonable κ-estimate error
/// while still flagging any genuine correctness bug.
const PARITY_TRIANGLE_CONST: f64 = 3.0;

fn bench_data_path(case: &str) -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest).join("..").join("..").join("bench_data").join(format!("{case}.bin"))
}

fn reference_path(case: &str) -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest)
        .join("..")
        .join("..")
        .join("bench_data")
        .join("reference_solutions")
        .join(format!("{case}.bin"))
}

struct Replay {
    grid: StokesGrid,
    eta_center: Field2D,
    drag_diag: Option<Field2D>,
    ctx: TangentContext,
    diag_vx: Vec<f64>,
    diag_vy: Vec<f64>,
    rhs_pack: Vec<f64>,
    tol: f64,
    max_iter: usize,
    diag_floor: f64,
    n_cells: usize,
}

fn build_replay(snap: &LinearStokesSnapshot) -> Replay {
    let grid = StokesGrid::new(snap.nx, snap.ny, snap.dx, snap.dy);
    let eta_center = field_from_vec(snap.eta_center.clone(), snap.nx, snap.ny);
    let drag_diag = snap
        .drag_diag
        .as_ref()
        .map(|v| field_from_vec(v.clone(), snap.nx, snap.ny));
    let ctx = TangentContext {
        eta_center: eta_center.clone(),
        c_center: field_from_vec(
            snap.tangent_c_center.clone().unwrap_or_else(|| vec![0.0; snap.n_cells()]),
            snap.nx,
            snap.ny,
        ),
        exx_center: field_from_vec(
            snap.tangent_exx_center.clone().unwrap_or_else(|| vec![0.0; snap.n_cells()]),
            snap.nx,
            snap.ny,
        ),
        eyy_center: field_from_vec(
            snap.tangent_eyy_center.clone().unwrap_or_else(|| vec![0.0; snap.n_cells()]),
            snap.nx,
            snap.ny,
        ),
        exy_corner: field_from_vec(
            snap.tangent_exy_corner.clone().unwrap_or_else(|| vec![0.0; snap.n_cells()]),
            snap.nx,
            snap.ny,
        ),
    };
    let mut rhs_pack = Vec::with_capacity(2 * snap.n_cells());
    rhs_pack.extend_from_slice(&snap.rhs_vx);
    rhs_pack.extend_from_slice(&snap.rhs_vy);
    Replay {
        grid,
        eta_center,
        drag_diag,
        ctx,
        diag_vx: snap.diag_vx.clone(),
        diag_vy: snap.diag_vy.clone(),
        rhs_pack,
        tol: snap.tol,
        max_iter: snap.max_iter,
        diag_floor: snap.diag_floor,
        n_cells: snap.n_cells(),
    }
}

fn solve_jacobi(replay: &Replay) -> (Vec<f64>, bool, usize) {
    let vjac = VelocityJacobi::from_diagonal(&replay.diag_vx, &replay.diag_vy, replay.diag_floor);
    let n = replay.n_cells;
    let cg = ConjugateGradient::new(replay.tol, replay.max_iter);
    let mut x_pack = vec![0.0f64; 2 * n];
    let b_scratch = replay.rhs_pack.clone();
    let mut tmp_ax = vec![0.0; n];
    let mut tmp_ay = vec![0.0; n];
    let mut matvec = |v: &[f64], out: &mut [f64]| {
        let (vx_in, vy_in) = v.split_at(n);
        let (out_x, out_y) = out.split_at_mut(n);
        apply_momentum(
            &replay.grid,
            &replay.eta_center,
            replay.drag_diag.as_ref(),
            vx_in,
            vy_in,
            &mut tmp_ax,
            &mut tmp_ay,
        );
        out_x.copy_from_slice(&tmp_ax);
        out_y.copy_from_slice(&tmp_ay);
        apply_tangent(&replay.grid, &replay.ctx, vx_in, vy_in, out_x, out_y);
    };
    let mut precond = |r: &[f64], z: &mut [f64]| vjac.apply(r, z);
    let stats = cg.solve(&mut matvec, &mut precond, &b_scratch, &mut x_pack);
    // Project to canonical zero-mean gauge, matching the reference.
    {
        let (vx, vy) = x_pack.split_at_mut(n);
        nullspace::project_velocity(vx, vy);
    }
    (x_pack, stats.converged(), stats.iterations)
}

fn solve_amg(replay: &Replay, snap: &LinearStokesSnapshot, cfg: AmgConfig) -> (Vec<f64>, bool, usize) {
    let a_picard =
        assemble_picard_csr(&replay.grid, &replay.eta_center, replay.drag_diag.as_ref());
    let precond = AmgPreconditioner::build(&a_picard, snap.n_cells(), cfg);
    let n = replay.n_cells;
    let cg = ConjugateGradient::new(replay.tol, replay.max_iter);
    let mut x_pack = vec![0.0f64; 2 * n];
    let b_scratch = replay.rhs_pack.clone();
    let mut tmp_ax = vec![0.0; n];
    let mut tmp_ay = vec![0.0; n];
    let mut matvec = |v: &[f64], out: &mut [f64]| {
        let (vx_in, vy_in) = v.split_at(n);
        let (out_x, out_y) = out.split_at_mut(n);
        apply_momentum(
            &replay.grid,
            &replay.eta_center,
            replay.drag_diag.as_ref(),
            vx_in,
            vy_in,
            &mut tmp_ax,
            &mut tmp_ay,
        );
        out_x.copy_from_slice(&tmp_ax);
        out_y.copy_from_slice(&tmp_ay);
        apply_tangent(&replay.grid, &replay.ctx, vx_in, vy_in, out_x, out_y);
    };
    let mut precond_fn = |r: &[f64], z: &mut [f64]| precond.apply(r, z);
    let stats = cg.solve(&mut matvec, &mut precond_fn, &b_scratch, &mut x_pack);
    {
        let (vx, vy) = x_pack.split_at_mut(n);
        nullspace::project_velocity(vx, vy);
    }
    (x_pack, stats.converged(), stats.iterations)
}

fn relative_max_diff_vs_reference(x: &[f64], ref_sol: &ReferenceSolution) -> f64 {
    let n = ref_sol.x_vx.len();
    assert_eq!(x.len(), 2 * n);
    let norm_ref = ref_sol
        .x_vx
        .iter()
        .chain(ref_sol.x_vy.iter())
        .map(|v| v.abs())
        .fold(0.0_f64, f64::max);
    if norm_ref == 0.0 {
        return 0.0;
    }
    let mut max_diff = 0.0_f64;
    for k in 0..n {
        max_diff = max_diff.max((x[k] - ref_sol.x_vx[k]).abs());
        max_diff = max_diff.max((x[n + k] - ref_sol.x_vy[k]).abs());
    }
    max_diff / norm_ref
}

fn check_scalar_parity(case: &str) {
    // --- Load snapshot + reference ---
    let snap = match LinearStokesSnapshot::load(bench_data_path(case)) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("[skip] {}: {}", case, e);
            return;
        }
    };
    let ref_sol = match ReferenceSolution::load(reference_path(case)) {
        Ok(r) => r,
        Err(e) => {
            panic!(
                "{}: reference missing at {} — run `cargo run --release --bin gen_reference_solutions -- --all`. ({})",
                case,
                reference_path(case).display(),
                e,
            );
        }
    };

    // --- Compute derived threshold ---
    let replay = build_replay(&snap);
    let tol_test = replay.tol;
    let tol_ref = ref_sol.tol_ref_achieved;
    let kappa = ref_sol.kappa_estimated;
    let threshold = PARITY_TRIANGLE_CONST * kappa * (tol_test + tol_ref);

    // --- Solve both paths and project to canonical gauge ---
    let (x_j, conv_j, iters_j) = solve_jacobi(&replay);
    let (x_a, conv_a, iters_a) = solve_amg(&replay, &snap, AmgConfig::default());

    let rel_j = relative_max_diff_vs_reference(&x_j, &ref_sol);
    let rel_a = relative_max_diff_vs_reference(&x_a, &ref_sol);

    eprintln!(
        "[parity] {:<22} κ={:.2e}  tol_test={:.0e}  tol_ref={:.2e}  threshold={:.3e}",
        case, kappa, tol_test, tol_ref, threshold,
    );
    eprintln!(
        "[parity] {:<22}   Jacobi (conv={}, iters={}): rel_diff_vs_ref = {:.3e}",
        case, conv_j, iters_j, rel_j,
    );
    eprintln!(
        "[parity] {:<22}   AMG    (conv={}, iters={}): rel_diff_vs_ref = {:.3e}",
        case, conv_a, iters_a, rel_a,
    );

    assert!(
        conv_j,
        "{}: JacobiCG did not converge at tol={:.0e}",
        case, tol_test
    );
    assert!(
        conv_a,
        "{}: AmgCG did not converge at tol={:.0e}",
        case, tol_test
    );
    assert!(
        rel_j <= threshold,
        "{}: JacobiCG rel_diff_vs_ref {:.3e} exceeds threshold {:.3e}",
        case, rel_j, threshold
    );
    assert!(
        rel_a <= threshold,
        "{}: AmgCG rel_diff_vs_ref {:.3e} exceeds threshold {:.3e}",
        case, rel_a, threshold
    );
}

#[test]
fn scalar_parity_step0_quiescent() {
    check_scalar_parity("step0_quiescent");
}

#[test]
fn scalar_parity_step3_floor_yielding() {
    check_scalar_parity("step3_floor_yielding");
}

#[test]
fn scalar_parity_step6_voronoi() {
    check_scalar_parity("step6_voronoi");
}

#[test]
fn scalar_parity_step7_slab_off() {
    check_scalar_parity("step7_slab_off");
}
