//! Step 7 regression smoke test — zero-cost-when-disabled
//! invariant.
//!
//! Verifies that a Step 6-physics-shape run with
//! `SlabPullConfig::Disabled` produces:
//! - No slab-pull diagnostics (all Step 7 fields `None`/empty).
//! - Same ballpark wallclock, CG iters, Newton outcome distribution
//!   as a Step 6 run of the same config — no overhead from the
//!   Step 7 machinery when it is structurally bypassed.
//! - Scalar parity on `mass_conservation_residual`: Closed-mode
//!   bilan should still hit machine noise when slab-pull is off.
//!
//! The 20-step run is deliberately short — we are checking the
//! absence of regression, not the physics. A full-fledged 300-step
//! comparison vs the live Step 6 physics report lives inside the
//! Step 7 regression report generated by the binary.

use std::path::PathBuf;

use ymir_core::tectonics_v2::basal_drag::{BasalDragConfig, BasalDragLaw};
use ymir_core::tectonics_v2::boundaries::{BoundaryConfig, BoundaryRates};
use ymir_core::tectonics_v2::diagnostics::harness::{
    BaselineConfig, ForceKind, NonlinearChoice, build_force, run_baseline,
};
use ymir_core::tectonics_v2::presets::{Preset, YieldingConfig};
use ymir_core::tectonics_v2::recycling::RecyclingConfig;
use ymir_core::tectonics_v2::rheology::YieldingLaw;
use ymir_core::tectonics_v2::scales::Scales;
use ymir_core::tectonics_v2::slab::SlabPullConfig;
use ymir_core::tectonics_v2::voronoi::VoronoiConfig;

fn build_step6_shape_config(slab: SlabPullConfig) -> BaselineConfig {
    let nx = 64;
    let ny = 64;
    let scales = Scales::default();
    let preset = Preset::by_name("dynamic-accidented").unwrap();
    let vcfg = VoronoiConfig { num_plates: 8, continental_ratio: 0.3 };
    let rates =
        BoundaryRates { k_sub: 0.5, k_arc: 0.0, k_spread: 0.0, k_coll_v: 0.0, k_rift_v: 0.0 };
    let boundary = BoundaryConfig::enabled_voronoi_closed(
        nx,
        ny,
        &vcfg,
        42,
        rates,
        RecyclingConfig::default(),
    )
    .expect("recycling config valid");
    let force = build_force(ForceKind::Gpe, &scales, 10.0, 1.0);
    BaselineConfig {
        seed: 42,
        grid_nx: nx,
        grid_ny: ny,
        domain_lx: 1.0,
        domain_ly: 1.0,
        steps: 20,
        cfl_factor: 0.3,
        total_time_nondim: 0.4, // Δt = 0.02 × 20
        preset,
        nonlinear: NonlinearChoice::Newton,
        newton_cfg: Default::default(),
        picard_cfg: Default::default(),
        heightmap_fractions: Vec::new(),
        output_dir: PathBuf::from("target/v2_step7_regression_smoke_scratch"),
        force,
        force_kind: ForceKind::Gpe,
        sinusoidal_amplitude: 0.0,
        s_perturbation_amplitude: 0.2,
        yielding: YieldingConfig::Enabled(YieldingLaw { bi: 0.15, ..Default::default() }),
        basal_drag: BasalDragConfig::Enabled(BasalDragLaw { br: 0.05, ..BasalDragLaw::default() }),
        boundary,
        boundary_layout_name: "voronoi_seed42_n8".into(),
        slab_pull: slab,
        mantle: ymir_core::tectonics_v2::mantle::MantleConfig::Disabled,
        cratonic: ymir_core::tectonics_v2::cratonic::CratonicConfig::Disabled,
        capture: None,
        linear_solver: Default::default(),
    }
}

#[test]
fn slab_disabled_produces_no_step7_diagnostics_and_parity_on_scalars() {
    // Disabled run — the regression target setup.
    let cfg_off = build_step6_shape_config(SlabPullConfig::Disabled);
    let r_off = run_baseline(&cfg_off);
    let na_off = r_off.metrics.newton.as_ref().expect("newton aggregate");

    // 1. Zero-cost invariant: all Step 7 metrics are `None` / empty.
    assert!(na_off.sp_diagnostic.is_none(), "sp_diagnostic must be None under Disabled");
    assert!(na_off.tau_slab_diagnostic.is_none());
    assert!(na_off.k_slab_accum_diagnostic.is_none());
    assert!(na_off.slab_m_mean_series.is_empty());
    assert!(na_off.slab_m_max_series.is_empty());
    assert!(na_off.peak_f_slab_run.is_none());
    assert!(na_off.peak_f_gpe_run.is_none());
    assert!(na_off.f_slab_to_f_gpe_ratio_mean.is_none());

    // 2. Mass-balance sanity — with mantle_loss_fraction = 0 and
    //    slab off, the Step 6 Closed-mode bilan should still hit
    //    machine noise.
    let residual = na_off.mass_conservation_residual.expect("Closed mode residual");
    assert!(
        residual < 1.0e-6,
        "mass_conservation_residual = {:.3e} should be < 1e-6 under Closed mode + slab off",
        residual,
    );

    // 3. Sanity: the disabled run should have completed 20 steps.
    assert_eq!(r_off.metrics.steps, 20);
    assert!(r_off.metrics.cg_iter_mean > 0.0);
}

#[test]
fn slab_disabled_run_matches_newton_convergence_rate_with_full_step6_setup() {
    // Ensures Newton still converges at the same rate when slab-pull
    // is off: if the harness wiring added accidental side-effects,
    // this would catch it.
    let cfg = build_step6_shape_config(SlabPullConfig::Disabled);
    let r = run_baseline(&cfg);
    let na = r.metrics.newton.as_ref().expect("newton aggregate");
    let (conv, stalled, diverged, capped) = na.outcome_percentages();
    // At 20 steps of the Step 6 Voronoi-physics setup, Newton should
    // be 100% converged (Step 6 physics report: 100% converged at 300
    // steps). Any stall/diverge/cap signals a real regression.
    assert!(
        conv > 99.9,
        "Newton converged rate = {:.1}% (stalled={}, diverged={}, capped={}). Expected 100%.",
        conv,
        stalled,
        diverged,
        capped,
    );
}
